CREATE TABLE IF NOT EXISTS `cjohnson_qu5773oo`.`BTC_CLASS` (
  `CLS_CLASS_ID` VARCHAR(7) UNIQUE NOT NULL,
  `CLS_CLASS_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CLS_CLASS_ID`));
  
  CREATE TABLE IF NOT EXISTS `cjohnson_qu5773oo`.`BTC_STUDENT` (
  `STDNT_STUDENT_ID` INT UNIQUE NOT NULL auto_increment,
  `STDNT_FIRST_NAME` VARCHAR(45) NOT NULL,
  `STDNT_LAST_NAME` VARCHAR(45) NOT NULL,
  `STDNT_GENDER` VARCHAR(1) NOT NULL,
  `STDNT_COHORT` VARCHAR(1) NOT NULL DEFAULT '$',
  PRIMARY KEY (`STDNT_STUDENT_ID`));

ALTER TABLE `cjohnson_qu5773oo`.`BTC_STUDENT`(
	`STDNT_STUDENT_ID` AUTO_INCREMENT=100);

CREATE TABLE IF NOT EXISTS `cjohnson_qu5773oo`.`BTC_CLASS_MEMBERS` (
  `CMBR_ID` INT UNIQUE NOT NULL auto_increment, 
  `CMBR_CLASS_ID` VARCHAR(7) UNIQUE NOT NULL,
  `CMBR_STUDENT_ID` INT NOT NULL,
  PRIMARY KEY (`CMBR_ID`),
  CONSTRAINT `CMBR_CLASS_ID`
    FOREIGN KEY (`CMBR_CLASS_ID`)
    REFERENCES `cjohnson_qu5773oo`.`BTC_CLASS` (`CLS_CLASS_ID`),
  CONSTRAINT `CMBR_STUDENT_ID`
    FOREIGN KEY (`CMBR_STUDENT_ID`)
    REFERENCES `cjohnson_qu5773oo`.`BTC_STUDENT` (`STDNT_STUDENT_ID`));
  

