<?php
  $getQuestions = "SELECT QSTNS_QESTION as question FROM cjohnson_qu5773oo.BTC_QUESTIONS";
  $fetchSurveys = "SELECT SRVY_ANSWER_ONE, SRVY_COMMENT_ONE, SRVY_ANSWER_TWO, SRVY_COMMENT_TWO,
    SRVY_ANSWER_THREE, SRVY_COMMENT_THREE, SRVY_ANSWER_FOUR, SRVY_COMMENT_FOUR, SRVY_ANSWER_FIVE,
    SRVY_COMMENT_FIVE, SRVY_ID as surveyID, SRVY_CMBR_ID as cmbrID, STDNT_FIRST_NAME as firstName,
    STDNT_LAST_NAME as lastName, CLS_CLASS_NAME as className
      FROM cjohnson_qu5773oo.BTC_SURVEY JOIN cjohnson_qu5773oo.BTC_CLASS_MEMBERS on SRVY_CMBR_ID = CMBR_ID
      JOIN cjohnson_qu5773oo.BTC_STUDENT on CMBR_STUDENT_ID = STDNT_STUDENT_ID
      JOIN cjohnson_qu5773oo.BTC_CLASS on CLS_CLASS_ID = CMBR_CLASS_ID";
  $getQuestions = "SELECT QSTNS_ONE,QSTNS_TWO,QSTNS_THREE, QSTNS_FOUR, QSTNS_FIVE FROM cjohnson_qu5773oo.BTC_QUESTIONS";
  $insertStudent = "INSERT INTO cjohnson_qu5773oo.STUDENT (STDNT_STUDENT_ID, STDNT_FIRST_NAME, STDNT_LAST_NAME, STDNT_GENDER, STDNT_COHORT) VALUES '$fname' '$lname' '$course' '$cohort' '$gender'";
  $deleteSurvey = "DELETE FROM cjohnson_qu5773oo.BTC_SURVEY WHERE SRVY_ID = $_POST['surveyToDelete']";
?>
